name: GitHub Actions Build Test

on: repository_dispatch

env:
  NAME: ${{ github.event.client_payload.name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: client payload
      run: 'echo "field: ${{ github.event.client_payload.name }}"'
    - name: setup
      run: npm install
    - name: hello stranger
      run: npm run hello
    - name: hello Joost
      run: npm run hello:joost
    - name: hello payload
      run: node src/hello.js


